### ISSUE TITLE
初めて起動した際のDeviseのエラーについて

### ISSUE THREAD

**Issue by ms2sato** [tedexample/shumishareca#9]
今、どのように対応されていますか〜？

```
 (master) $ bin/rake db:migrate
/Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass/version.rb:2: warning: already initialized constant Bootstrap::VERSION
/Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-4.1.1/lib/bootstrap/version.rb:2: warning: previous definition of VERSION was here
/Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-sass-3.3.7/lib/bootstrap-sass/version.rb:3: warning: already initialized constant Bootstrap::BOOTSTRAP_SHA
/Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootstrap-4.1.1/lib/bootstrap/version.rb:3: warning: previous definition of BOOTSTRAP_SHA was here
/Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/devise-4.4.3/lib/devise/rails/routes.rb:500:in `raise_no_secret_key': Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = 'c1dfd8fc100c31407292e7ca4c1a0a4d3126585588fde74a1b1d396365768414bd5760ee5c12af9c259f0afd37e3c52284ce6138d6b5139649c488d752de0ea4'

Please ensure you restarted your application after installing Devise or setting the key.
 (RuntimeError)
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/devise-4.4.3/lib/devise/rails/routes.rb:228:in `devise_for'
	from /Users/ms2/dev/work/training/kitakatsu/shumishareca/config/routes.rb:8:in `block in <main>'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:414:in `draw'
	from /Users/ms2/dev/work/training/kitakatsu/shumishareca/config/routes.rb:1:in `<main>'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:57:in `block in load_paths'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:57:in `each'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:57:in `load_paths'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:20:in `reload!'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:43:in `block in updater'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/file_update_checker.rb:83:in `execute'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:44:in `updater'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application/routes_reloader.rb:33:in `execute_if_updated'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:130:in `block in <module:Finisher>'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
	from /Users/ms2/dev/work/training/kitakatsu/shumishareca/config/environment.rb:5:in `<main>'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ms2/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by tedexample** [comment]
deviseを触り出してmigrateした時に同じエラーを吐いてましたので、
このlogの中にあるような
config.secret_key = 'c1dfd8f.....
をconfig/initialize/devise.rb にコピペで貼り付けました。
が、今自分のファイルを見ると抜けてました。

**Comment by ms2sato** [comment]
@tedexample なるほど。これにはいくつか対応方法があるのですが、一旦それで良いですよ。pushしといてくださいー。

**Comment by ms2sato** [comment]
だいじょうぶそう。close

**Comment by ms2sato** [comment]
まだ反映されてなかったぽい。一応open

**Comment by tedexample** [comment]
rake secretでパスワードを再発行して更新してみました。
